### ISSUE TITLE
Flask-admin 1.4.1

### ISSUE THREAD

**Issue by sodre** [conda-forge/flask-admin-feedstock#3]
@pmlandwehr 

Sorry to do this again, can you add flask-admin 1.4.1 as well, this is for airflow? 

I am happy to send the PR, but since it "needs" to go backwards I am not sure how you want to handle it.

**Comment by pmlandwehr** [comment]
Just set up an alternate branch and am pushing to that - see https://github.com/conda-forge/flask-admin-feedstock/pull/4

**Comment by sodre** [comment]
Thank you again!
